# Generated by Django 3.1.7 on 2021-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='desciption',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='specs',
            field=models.CharField(default='', max_length=120),
        ),
    ]
