# Generated by Django 3.1.7 on 2021-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20210411_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
