# Generated by Django 3.1.7 on 2021-04-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20210411_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_add', models.CharField(max_length=220)),
                ('user', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('dispatched', 'dispatched'), ('cancelled', 'cancelled')], default='orderd', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile')),
            ],
        ),
    ]
