# Generated by Django 3.1.7 on 2021-04-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20210412_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
