# Generated by Django 3.1.7 on 2021-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
