# Generated by Django 3.1.7 on 2021-04-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_auto_20210413_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
